#    /$$$$$$$                                  /$$                     /$$  /$$$$$$                  /$$ /$$                  /$$$$$$       /$$$$$$
#    | $$__  $$                                | $$                    | $$ /$$__  $$                | $$|__/                 /$$__  $$     /$$$_  $$
#    | $$  \ $$  /$$$$$$   /$$$$$$   /$$$$$$$ /$$$$$$    /$$$$$$   /$$$$$$$| $$  \ $$ /$$   /$$  /$$$$$$$ /$$  /$$$$$$       |__/  \ $$    | $$$$\ $$
#    | $$$$$$$  /$$__  $$ /$$__  $$ /$$_____/|_  $$_/   /$$__  $$ /$$__  $$| $$$$$$$$| $$  | $$ /$$__  $$| $$ /$$__  $$        /$$$$$$/    | $$ $$ $$
#    | $$__  $$| $$  \ $$| $$  \ $$|  $$$$$$   | $$    | $$$$$$$$| $$  | $$| $$__  $$| $$  | $$| $$  | $$| $$| $$  \ $$       /$$____/     | $$\ $$$$
#    | $$  \ $$| $$  | $$| $$  | $$ \____  $$  | $$ /$$| $$_____/| $$  | $$| $$  | $$| $$  | $$| $$  | $$| $$| $$  | $$      | $$          | $$ \ $$$
#    | $$$$$$$/|  $$$$$$/|  $$$$$$/ /$$$$$$$/  |  $$$$/|  $$$$$$$|  $$$$$$$| $$  | $$|  $$$$$$/|  $$$$$$$| $$|  $$$$$$/      | $$$$$$$$ /$$|  $$$$$$/
#    |_______/  \______/  \______/ |_______/    \___/   \_______/ \_______/|__/  |__/ \______/  \_______/|__/ \______/       |________/|__/ \______/
#
# BoostedAudio 2.0 - ProximityVoiceChat and Music | Made by SuperMax_8
# Wiki: https://supermax-8.gitbook.io/boostedaudio/

# Show debug messages, websocket connections and others, useful if you want to come on the discord for support
debugMode: false

# Update notifications and others
notification: true

# Set the working mode of the plugin
# - Diffuser: This will make the server diffuse to the mainProxyWebsocketLink
# - Host: Make this server the main server (default mode for spigot)
# Example the multiserv/multiproxy setup you can do this:
# - Proxy1: MainHost host mode
# - Proxy2: Diffuser mode
# - Spigot1,2,3,4: Diffuser mode
diffuser: false
# Use the same param as the clientWebSocketLink in the main proxy config
mainProxyWebsocketLink: wss://localhost:8081
# If this is the spigot config: let it empty and a secret will be generated, put it in the bungee config same place
# If this a proxy config: put the secrets of the spigot servers here
# You can also manually define the secret here (Use unique strong secret)
secrets:
  - ""
# The name of the server used on the proxy (only for diffuser servers)
# Diffuser Spigot: It's the name you see when you do /server
# Diffuser Proxy: Use a random name
proxyServerName: "lobby"

# Web client
client-link: https://localhost:8080
# The self-host web server, useful to host the audio panel and audio files
autoHost: true
autoHostPort: 8080

# Web Socket
clientWebSocketLink: wss://localhost:8081
webSocket:
  webSocketPort: 8081
  webSocketHostName: 0.0.0.0

# SSL, ssl will be used for WebClient if enabled, and WebSocket
# Even ssl option is false the socket & autohost will still be https and wss with a self-signed certificate
# You can use a .jks file OR use 2 pem files named cert.pem and key.pem
ssl:
  ssl: false
  keystorePassword: "YOUR_PASSWORD"
  keystoreFileName: "keystore.jks"

# Stun & Turn servers
# These servers are used for webrtc (the proximity chat technology)
# By default, the plugin uses free ones
# If you have a lot of players or problems with inconsistent proximity chat connections,
# using turn made for your server can resolve proximity chat connections problems
# https://github.com/coturn/coturn Free open src project to host yourself a stun/turn server
# https://www.metered.ca/tools/openrelay/ They have a free plan with 50GB for stun/turn servers
# If useCustomIce is false it will use default iceServers, set this param to true to provide custom ice
useCustomIce: false
iceServers:
  - "{urls: 'stun:stun2.l.google.com:19302'},"
  - "{urls: 'turn:freestun.net:3478', username: 'free', credential: 'free'}"

#VoiceChat
voicechat:
  # If the system is enabled
  voicechat: true

  # The maximum distance at which players can be heard
  maxVoiceDistance: 30

  # The calculation model for the distance volume attenuation
  # linear, inverse, exponential
  distanceModel: exponential

  # This property defines the distance from which the sound begins to attenuate
  refDistance: 4

  # This property controls how quickly the sound attenuates as distance increases
  rolloffFactor: 1

# Send the connection message when the player connects
sendOnConnect: true
# Delay of the connection message in tick when the player connects
sendOnConnectDelay: 30

# Send a packet map in the second hand
sendQRcodeOnConnect: true

# The file format of the audio
# wav, m4a, webm, ogg, mp3, flac
# Using, for example, mp3 can reduce the file size and the time to download
# Using flac or wav can up the audio quality and size
audioDownloaderFormat: "wav"

# Messages
# If you want to add the generated url in the message, for example, geyser compatibility you can add the placeholder {link} in the message
# connectionMessage: "§6Join the audio client by clicking here! Link: {link}"
# You can use a simple String or a list of strings here for lines
connectionMessage:
  - "§6Join the audio client by clicking here!"
connectionHoverMessage: "Click here"

# QRcode map item name
qrCodeTitle: "§6Scan me to connect to the audio"

# BoostedAudio placeholders from PlaceHolderAPI config
connectedSymbol: "§f🔊"
mutedSymbol: "§c🔇"
notconnectedSymbol: ""

# Don't use if you are not sure
# If this is true, it means that the plugin will no longer auto params the client (modify the index.html in webhost directory)
# this property allows you to fully customize the client by modifying the code of the client
customClient: false

# WORKS ONLY WITH THE PREMIUM VERSION
# Custom placeholder in the client html, if you custom the client you even can add new placeholder if you need it,
# inside placeholder you can use html directly (if the placeholder target is not a tag parameter)
# if you want more customization with like images or things

# Others skin api
# https://cravatar.eu/avatar/
# https://crafatar.com/
# https://crafthead.net/
# You can use the variables uuid or username, for the player name or uuid
clientConfig:
  - '{skinAPI}="https://cravatar.eu/avatar/" + username'
  - "{mainColor}=#262c3c"
  - "{primaryColor}=#202433"
  - "{secondaryColor}=#205295"
  - "{accentColor}=#4797de"
  - "{bg-img}=https://i.imgur.com/6MelMqC.jpg"
  - "{bg-opacity}=80"
  - "{title}=BoostedAudio"
  - "{page-title}=BoostedAudio Client"
  - "{ambient-volume}=Ambient Volume"
  - "{voice-volume}=Voice Volume"
  - "{click-to-connect}=Click on the page to connect"
  - "{userList}=User List"
  - "{you-are-mute}=You have been muted by the server"
  - "{search-placeholder}=Search..."
  - "{user-count-label}=Players you can hear:"
  - "{settings-title}=Settings"
  - "{settings-label}=Parameters of the audio client"
  - "{settings-microphone-device-label}=Microphone Device"
  - "{settings-micThreshold-label}=Microphone sensitivity"
  - "{settings-micThreshold-description}=Sensivity of the microphone in dB, the noise bellow this dB amount will be cancel, the bar moving represent your current mic volume"
  - "{settings-noiseSuppression-label}=Noise Suppression"
  - "{settings-noiseSuppression-description}=Removes noise from your microphone audio"
  - "{settings-echoCancellation-label}=Echo Cancellation"
  - "{settings-echoCancellation-description}=Removes echo from your microphone audio"
  - "{settings-close-button-label}=Close Settings"
  - "{offline}=Offline"
  - "{offline-text}=The websocket is not connected, try reconnecting with a new in-game link, you can close this page"


# NEVER CHANGE THIS VALUE
config-version: 1