# Show debug messages, websocket connections and others
debugMode: false

# Web client (change http by https if you are using ssl)
client-link: http://localhost:8080
autoHost: true
autoHostPort: 8080

# SSL, ssl will be used for WebClient if enabled and websocket
ssl: false
keystorePassword: "YOUR_PASSWORD"
keystoreFileName: "keystore.jks"

# WebSocket
webSocketPort: 8081
webSocketHostName: localhost

# In game params
maxVoiceDistance: 30

# The calculation model for the distance volume attenuation
# linear, inverse, exponential
distanceModel: exponential

# This property defines the distance from which the sound begins to attenuate
refDistance: 3

# This property controls how quickly the sound attenuates as distance increases
rolloffFactor: 2


# Messages
connectionMessage: "ยง6Join the audio client by clicking here!"
connectionHoverMessage: "Click here"