# Show debug messages, websocket connections and others
debugMode: false

# Web client (change http by https if you are using ssl)
client-link: http://localhost:8080
autoHost: true
autoHostPort: 8080

# SSL, ssl will be used for WebClient if enabled and websocket
ssl:
  ssl: false
  keystorePassword: "YOUR_PASSWORD"
  keystoreFileName: "keystore.jks"

# WebSocket
webSocket:
  webSocketPort: 8081
  webSocketHostName: localhost

#VoiceChat
voicechat:
  # If the system is enabled
  voicechat: true

  # The maximum distance at which players can be heard
  maxVoiceDistance: 30

  # The calculation model for the distance volume attenuation
  # linear, inverse, exponential
  distanceModel: exponential

  # This property defines the distance from which the sound begins to attenuate
  refDistance: 4

  # This property controls how quickly the sound attenuates as distance increases
  rolloffFactor: 1

# Send the connection message when the player connects
sendOnConnect: true
# Delay of the connection message in tick when the player connects
sendOnConnectDelay: 30

# Don't use if you are not sure
# If this is true that means that the plugin will no longer auto params the client (modify the index.html in webhost directory)
# this property allows you to fully customize the client by modifying the code of the client
customClient: false

# Messages
connectionMessage: "ยง6Join the audio client by clicking here!"
connectionHoverMessage: "Click here"


clientConfig:
  # Custom Colors
  - "{mainColor}=#262c3c"
  - "{primaryColor}=#202433"
  - "{secondaryColor}=#205295"
  - "{accentColor}=#4797de"

  # Images
  - "{bg-img}=https://i.imgur.com/6MelMqC.jpg"
  # Messages
  - "{title}=BoostedAudio" # You can put html image here to set a logo
  - "{ambient-volume}=Ambient Volume"
  - "{voice-volume}=Voice Volume"
  - "{click-to-connect}=Click on the page to connect"
  - "{sidebar-content}=Sidebar Content"
  - "{userList}=User List"
  - "{search-placeholder}=Search..."
  - "{user-count-label}=Players you can hear:"

  # Texts for Settings
  - "{settings-title}=Settings"
  - "{settings-label}=Parameters of the audio client"
  - "{settings-microphone-device-label}=Microphone Device"
  - "{settings-close-button-label}=Close Settings"

  # Texts for Audio Control Buttons and Labels
  - "{ambient-volume-label}=Ambient Volume"
  - "{voice-volume-label}=Voice Volume"