name: BoostedAudio
version: '${project.version}'
main: fr.supermax_8.boostedaudio.spigot.BoostedAudioSpigot
api-version: '1.16'
authors:
  - SuperMax_8
description: Realtime music and proximity voice chat
website: https://www.spigotmc.org/resources/boostedaudio-%E2%9C%A8proximity-voice-chat-and-music.112942/
softdepend:
  - WorldGuard
commands:
  audio:
    aliases:
      - music
  boostedaudio:
    permission: boostedaudio.admin
    aliases:
      - ba